TRUNCATE TABLE person_order RESTART IDENTITY CASCADE;
TRUNCATE TABLE person_visits RESTART IDENTITY CASCADE;
TRUNCATE TABLE menu RESTART IDENTITY CASCADE;
TRUNCATE TABLE pizzeria RESTART IDENTITY CASCADE;
TRUNCATE TABLE person RESTART IDENTITY CASCADE;

//CASCADE - для обхода всех внешних ключей
//RESTART IDENTITY - для сброса идентификаторов(инкремента)

DROP TABLE IF EXISTS person_order CASCADE;
DROP TABLE IF EXISTS person_visits CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS pizzeria CASCADE;
DROP TABLE IF EXISTS person CASCADE;